### ISSUE TITLE
Getting `Minified React error` error when try to open a reference table

### ISSUE THREAD

**Issue by PramodTKodag** [drizzle-team/drizzle-kit-mirror#578] opened 2024-09-23 09:24 UTC
```
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at eY (https://local.drizzle.studio/index.js:48:18191)
    at Object.ssl [as useMemo] (https://local.drizzle.studio/index.js:48:21923)
    at am.useMemo (https://local.drizzle.studio/index.js:19:6321)
    at bol.useSyncExternalStoreWithSelector (https://local.drizzle.studio/index.js:66:395)
    at fat (https://local.drizzle.studio/index.js:66:1227)
    at i (https://local.drizzle.studio/index.js:66:1538)
    at https://local.drizzle.studio/index.js:286:32621
    at nVl (https://local.drizzle.studio/index.js:402:67070)
    at https://local.drizzle.studio/index.js:499:4170
    at Array.map (<anonymous>)
```

This is the error appearing up on a screen when try to open a relational table using drizzle studio

**Comment by MegaMind98** [comment] 2024-09-23 21:54
Duplicate of #573

**Comment by AndriiSherman** [comment] 2024-09-24 08:46
Closed as duplicate

**Closed by AndriiSherman** 2024-09-24 08:46 UTC
