### ISSUE TITLE
[BUG] "Please install latest version of drizzle-orm"

### ISSUE THREAD

**Issue by DwieDave** [drizzle-team/drizzle-kit-mirror#406] opened 2024-05-13 15:07 UTC
Hello,
I can't make the current drizzle-kit version work with my setup.
No matter what command I try I am getting this error:
<img width="466" alt="grafik" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/15933094/a19b7f2e-056a-4dd3-9cc0-047cb9654728">

I am suspecting that npm workspaces might interfere here.
When I installed both packages (kit and orm) in one of the workspaces (called backend) with the commands:
```bash
npm i -w backend drizzle-orm@latest
npm i -w backend -D drizzle-kit@latest
```

`drizzle-kit` is located in the `node_modules` directory in the project root and `drizzle-orm` is located in the backend-workspaces `node_modules`.

Heres what my sub-packages package.json entries look like:
   `"drizzle-orm": "^0.30.10"`

and under devDependencies:
    `"drizzle-kit": "^0.21.1"`

**Comment by petter** [comment] 2024-05-14 14:29
Also experiencing this in a npm workspaces project. Downgrading drizzle-kit to 0.21.0 fixed it for me.

**Comment by korcekj** [comment] 2024-05-15 16:47
Downgrading drizzle-kit to 0.21.0 did not help...

<img width="454" alt="Screenshot 2024-05-15 at 18 45 30" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/39954896/fa8a48c0-3b3e-49e1-86fe-d11690b49a5f">

Which combination of drizzle-kit and drizzle-orm works for sqlite?

**Comment by healqq** [comment] 2024-05-21 12:43
`npx(pnpx) drizzle-kit ....` doesn't seem to work for me, however npm(pnpm) `drizzle-kit ....` seems to work.
drizzle-kit: 0.21.2
drizzle-orm: 0.30.10

**Comment by OCA99** [comment] 2024-05-28 08:56
I need to run 0.21.2 due to [this](https://github.com/drizzle-team/drizzle-kit-mirror/issues/397) issue, but anything higher than 0.21.0 throws "Please install latest version of drizzle-orm".

Drizzle ORM version is 0.30.10. This is running within a npm workspaces project, same as @petter.

**Comment by leognmotta** [comment] 2024-05-30 21:41
same problem

**Comment by tomshaw650** [comment] 2024-05-31 11:26
Is this something to do with pnpm then? I'm also having trouble in a pnpm workspace with latest versions of drizzle-kit and drizzle-orm

**Comment by Jodldokus** [comment] 2024-05-31 13:23
same issue, updating drizzle-kit bricked it for me :(

**Comment by tomshaw650** [comment] 2024-05-31 13:28
as someone has said, I used npx instead and it worked.

**Comment by bruceharrison1984** [comment] 2024-05-31 21:07
same issue using NPM workspaces. Both drizzle-orm and drizzle-kit are only installed in a single workspace.

**Comment by maximemoreillon** [comment] 2024-06-04 22:24
I am having the same issue. I started a new project following [the instructions provided in the official documentation](https://orm.drizzle.team/docs/get-started-sqlite#better-sqlite3) and running `npx drizzle-kit push` fails with error 

```
drizzle-kit: v0.22.2
drizzle-orm: v0.29.5

This version of drizzle-kit requires newer version of drizzle-orm
Please update drizzle-orm package to the latest version 👍
```

**Comment by kevinswarner** [comment] 2024-06-05 03:25
I am also having this issue in a Turborepo setup.

error please install required packages: 'drizzle-orm'

drizzle-kit: ^0.22.2
drizzle-orm: ^0.31.1

I have an npm script...

"push": "drizzle-kit push"

which is located inside my database package inside the packages folder.

I run the command from the root of the monorepo...

npm run -w @repo/db push

**Comment by kevinswarner** [comment] 2024-06-06 17:58
The only way I could solve this in my Turborepo was to install drizzle-orm in the root of the monorepo per https://github.com/drizzle-team/drizzle-kit-mirror/issues/406#issuecomment-2142978648

**Comment by stianthaulow** [comment] 2024-06-07 10:03
I also had to install drizzle-orm in the root package.json of my npm workspaces monorepo in addition to having it in package.json in my app

Could this be caused by drizzle-kit only having drizzle-orm as a devDependency and not a regular dependency?

**Comment by ItsTarik** [comment] 2024-06-10 20:52
Even when i install `drizzle-orm` in the root of my monorepo **pnpm workspaces**(which i find not great) i still have the same error!
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/10453938/45f6eaf4-1af3-49cb-a73e-7bc8d54e2735)

**Comment by ItsTarik** [comment] 2024-06-11 16:56
> I need to run 0.21.2 due to [this](https://github.com/drizzle-team/drizzle-kit-mirror/issues/397) issue, but anything higher than 0.21.0 throws "Please install latest version of drizzle-orm".
> 
> Drizzle ORM version is 0.30.10. This is running within a npm workspaces project, same as @petter.

Not working within docker image in pnpm workspaces context ..

**Comment by felixgeissler** [comment] 2024-06-12 20:37
I'm also experiencing the same issue with workspaces in Yarn.

> > I was having the same issue. I started a new project following [the instructions provided in the official documentation](https://orm.drizzle.team/docs/get-started-sqlite#better-sqlite3) and running `npx drizzle-kit push` fails with error
> > ```
> > drizzle-kit: v0.22.2
> > drizzle-orm: v0.29.5
> > 
> > This version of drizzle-kit requires newer version of drizzle-orm
> > Please update drizzle-orm package to the latest version 👍
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I solved it by downgrading drizzle-kit to 0.21
> 
> this works, plus i get access to new features from drizzle-orm, like $onUpdate To be precise, i downgraded to 0.22.1.

This combination did not work for me though.

**Comment by samhsabin** [comment] 2024-06-21 05:45
Same error here

**Comment by luiz7727** [comment] 2024-06-22 11:08
I'm using turborepo and installing drizzle-orm on my root package.json worked

**Comment by Maxth47** [comment] 2024-06-28 06:19
My fix is :

`		"drizzle-kit": "0.22.1",
		"drizzle-orm": "^0.31.2",`

**Comment by AuJezus** [comment] 2024-06-29 14:18
I also experience this problem with turbo repo setup. The comment above fixed it for me.

**Comment by bestickley** [comment] 2024-07-04 00:35
I resolved this issue in my PNPM monorepo by updating all versions for drizzle-orm to the latest version. Seems like the issue was that drizzle-kit in a workspace with an up to date drizzle-orm was not resolving to correct version (in that workspace) but was rather resolving to older version from another workspace. Syncing all versions of drizzle-orm resolved issue.

**Comment by MincePie** [comment] 2024-07-04 11:30
> I resolved this issue in my PNPM monorepo by updating all versions for drizzle-orm to the latest version. Seems like the issue was that drizzle-kit in a workspace with an up to date drizzle-orm was not resolving to correct version (in that workspace) but was rather resolving to older version from another workspace. Syncing all versions of drizzle-orm resolved issue.

How did you discover that you had another workspace with drizzle installed that was overriding your drizzle installation in the project that gave you the issue? I cant find a way to solve this issue and am not sure where to look to find if I have the same issue as you. I'll find how to sync competing versions if I find that this is the problem. I'd be surprised if it is because about a month ago, I was able to run drizzle studio without this issue, and I haven't made any other projects since.

**Comment by colleyyyy** [comment] 2024-07-07 02:55
what is the fix for this issue? I tried the version that list above, but nothing work.

**Comment by bestickley** [comment] 2024-07-07 10:14
@MincePie, `pnpm ls -r "drizzle-kit"`
Something to look into is the new PNPM [Catalog](https://github.com/pnpm/rfcs/blob/main/text/0001-catalogs.md) dependency specifiers. I think it's in beta now, but something I plan to use to mitigate this problem and other similar problems I experience in my monorepo.

**Comment by MincePie** [comment] 2024-07-08 03:24
> @MincePie, `pnpm ls -r "drizzle-kit"` Something to look into is the new PNPM [Catalog](https://github.com/pnpm/rfcs/blob/main/text/0001-catalogs.md) dependency specifiers. I think it's in beta now, but something I plan to use to mitigate this problem and other similar problems I experience in my monorepo.

Thank you @bestickley - I'll explore this suggestion.

**Comment by justinwiley** [comment] 2024-07-11 19:17
@AndriiSherman any way to address this?  As it currently stands, following the instructions in https://orm.drizzle.team/kit-docs/overview in a new repo doesn't work due to this issue, so it's not possible to use drizzle-kit without backing down to an earlier version.

```
❯ pnpm add drizzle-orm postgres  # "^0.32.0", "^3.4.4"
pnpm add -D drizzle-kit  # "^0.23.0"
❯ pnpx drizzle-kit generate
drizzle-kit: v0.23.0


Please install latest version of drizzle-orm
```

**Comment by MincePie** [comment] 2024-07-11 19:21
@justinwiley i havent been able to find a version that works - and would also  appreciate if drizzle could identify which version works

**Comment by justinwiley** [comment] 2024-07-11 19:30
> @justinwiley i havent been able to find a version that works - and would also appreciate if drizzle could identify which version works

This one just worked for me:

https://github.com/drizzle-team/drizzle-kit-mirror/issues/406#issuecomment-2196221476

**Comment by f4z3k4s** [comment] 2024-07-12 11:09
> My fix is to install:
> 
> ```
> 		"drizzle-kit": "0.22.1",
> 		"drizzle-orm": "^0.31.2",
> ```

This doesn't work for me, just tried upgrading today. Neither do the latest versions.

**Comment by DevHumbleChris** [comment] 2024-07-24 07:30
It has worked for me, all you is just update the drizzle-orm
```bash
npm i drizzle-orm@latest
```
After updating: 👇👇👇
![image](https://github.com/user-attachments/assets/9a36ded3-70d2-4d94-93fe-0d1102cf0e07)

**Comment by Rukhsar** [comment] 2024-07-25 15:02
> It has worked for me, all you need is just update the drizzle-orm
> 
> ```shell
> npm i drizzle-orm@latest
> ```
> 
> After updating: 👇👇👇 ![image](https://private-user-images.githubusercontent.com/63234437/351618027-9a36ded3-70d2-4d94-93fe-0d1102cf0e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjAwMzUsIm5iZiI6MTcyMTkxOTczNSwicGF0aCI6Ii82MzIzNDQzNy8zNTE2MTgwMjctOWEzNmRlZDMtNzBkMi00ZDk0LTkzZmUtMGQxMTAyY2YwZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE1MDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZjEwMjgzMmRjZDIzZTA0YjUzYTFmYTFkYjU0MzdjNmZiYzhhNzk5ZDI1OTMzZTY5MjMwMTUzNDFlMDUxNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1wqrU8wulrLBjEGuYww11Ym9fhsFeM6bPfbXsJd98M)

Using the latest version helped me.

**Comment by tfazekas** [comment] 2024-07-25 15:47
Using the latest is alright for generating migrations, but on the latest `drizzle-kit up` that should update the spapshot files is not working properly when using `dialect=postgresql`.

To update the snapshots I had to use `drizzle-kit@0.22.1` first. After it ran successfully, updating to the latest fixed the migration generation.

Would be good to know, that `drizzle-kit up` does not work on the latest for postgresl as stated here:
https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210

**Comment by incompletude** [comment] 2024-07-29 14:30
The problem is that drizzle-kit have a devDep to drizzle-orm set to exactly "0.32.0-85c8008". And your project settings depends on "0.32.1" or "0.32.0".

**Comment by incompletude** [comment] 2024-07-29 16:13
I found that for some reason `drizzle-orm` has `react` as peerDep. So if you are using a monorepo, it can cause `drizzle-orm` to not be hoisted. Having `drizzle-kit` hoisted while `drizzle-orm` is not, causes the `install latest version` error. 

In my case, adding the following section to my root package.json fixed the problem:

```
  "overrides": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
```

**Comment by alpertuna** [comment] 2024-07-29 17:28
I use monorepo for both frontend and backend with npm workspace,
as @incompletude mentioned about react,
- I just tried to uninstall react from frontend,
- Then installed drizzle-orm and drizzle-kit to backend,
- Then installed react back to frontend

Now everything works fine. Thank you @incompletude for your suggestion, it is a weird dependency issue.

**Comment by incompletude** [comment] 2024-07-29 17:35
> I use monorepo for both frontend and backend with npm workspace, as @incompletude mentioned about react,
> 
> * I just tried to uninstall react and react-dom from frontend,
> * Then installed drizzle-orm and drizzle-kit to backend,
> * Then installed react back to frontend
> 
> Now everything works fine. Thank you @incompletude for your suggestion, it is a weird dependency issue.

the problem with this solution is that if you make a clean install you will face the problem again, meaning it will not work on ci/cd

**Comment by alpertuna** [comment] 2024-07-29 17:44
> > I use monorepo for both frontend and backend with npm workspace, as @incompletude mentioned about react,
> > 
> > * I just tried to uninstall react and react-dom from frontend,
> > * Then installed drizzle-orm and drizzle-kit to backend,
> > * Then installed react back to frontend
> > 
> > Now everything works fine. Thank you @incompletude for your suggestion, it is a weird dependency issue.
> 
> the problem with this solution is that if you make a clean install you will face the problem again, meaning it will not work on ci/cd. you will problaly need the overrides too.

My package-lock.json which is also pushed to remote, is changed and probably compatible dependencies are now logged there.
I tried deleting node_modules and running `npm ci` and everything still works. But I noted your override suggestion and I will use that too if I encounter the same issue on another environment like ci/cd.

**Comment by Maxth47** [comment] 2024-07-29 19:39
good finding, thank you @incompletude 
Could you explain why do we need to `override` :  "react-dom": "^18.3.1"  ? 
I dont see react-dom listed as `peerDependencies` in the drizzle-orm package

**Comment by robertkibet** [comment] 2024-07-30 10:23
This was abit frustrating initialy. 
I am working with PNPM workspaces.

✅  I managed to solve it by installing drizzle-kit and drizzle-orm to the root of my monorepo instead of the target `packages/server`

This is my monorepo structure:
```bash
packages
  - server
  - frontend
```


1. I removed both `drizzle-orm` and `drizzle-kit` from the specific package, which is `server` in my case
2. install them in the root of my monorepo `./package.json`

```bash
# install in root package.json
pnpm add drizzle-orm -w
pnpm add drizzle-kit -D -w
```

**Comment by iiAbady** [comment] 2024-08-01 14:08
I had drizzle-kit installed globally in my machine. When trying to execute the commands `drizzle-kit up` or `drizzle-kit generate` I had the above-mentioned problem. Executing the scripts in my package.json made the commands worked just fine (even though the drizzle kit version in my project and globally is identical).

**Comment by mmd-moradi** [comment] 2024-08-06 19:53
To fix the problem (I'm using Turborepo):

First, I added the following to my root `package.json`:

```json
"overrides": {
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
}
```

The reason for this is that there are dependency issues between React 19 and Drizzle. I'm not sure of the exact details, but I encountered the same issue in another Next.js project as well. Thanks to @incompletude for the tip.

Next, in each of your apps inside the `/apps` directory, open `package.json` and change the versions of `react` and `react-dom` to `18.2.0`, and `next` to `14` (e.g., `14.2.3`). Save the changes, delete the root `node_modules` directory, and run `npm install` (make sure you are in the root of the project).

Then, create your database folder inside `/packages` and set up your `package.json` with the following dependencies:

```json
"devDependencies": {
  "drizzle-kit": "^0.22.1"
},
"dependencies": {
  "dotenv": "^16.4.5",
  "drizzle-orm": "^0.31.2",
  "postgres": "^3.4.4"
}
```

Run `npm install` in your database package folder (for me, it's `/packages/db`), and follow this [guide](https://orm.drizzle.team/kit-docs/quick). 

In the end, when you run `npm run generate` inside your `db` package, you should no longer face the error.

**Comment by flmn** [comment] 2024-08-20 05:34
same problem with:
"drizzle-orm": "^0.33.0",
"drizzle-kit": "^0.24.0",

I check the source code:
`assertOrmCoreVersion = async () => {
      try {
        const { compatibilityVersion } = await import("drizzle-orm/version");
        await import("drizzle-orm/relations");
        if (compatibilityVersion && compatibilityVersion === requiredApiVersion) {
          return;
        }
        if (!compatibilityVersion || compatibilityVersion < requiredApiVersion) {
          console.log(
            "This version of drizzle-kit requires newer version of drizzle-orm\nPlease update drizzle-orm package to the latest version \u{1F44D}"
          );
        } else {
          console.log(
            "This version of drizzle-kit is outdated\nPlease update drizzle-kit package to the latest version \u{1F44D}"
          );
        }
      } catch (e2) {
        console.log("Please install latest version of drizzle-orm");
      }
      process.exit(1);
    };`

The printed message is because of there is an other exception, not a compatibility version problem.

**Comment by ShaheerCH** [comment] 2024-09-25 03:22
Maybe it works for but in my case running 
```npx drizzle-kit generate```
worked

**Comment by benjick** [comment] 2024-09-25 06:02
Any suggestions for using pnpm with different versions of drizzle-kit/orm?

I'm running Payload CMS which isn't up to date with their drizzle-orm, but I want to update drizzle in my nextjs app. I've tried not hoisting drizzle-*, I've tried `overrides` for only my payload app. I can't get drizzle-kit to use the correct version, either the payload app or the nextjs app breaks.

**Comment by ShaheerCH** [comment] 2024-09-25 06:29
> Any suggestions for using pnpm with different versions of drizzle-kit/orm?
> 
> I'm running Payload CMS which isn't up to date with their drizzle-orm, but I want to update drizzle in my nextjs app. I've tried not hoisting drizzle-*, I've tried `overrides` for only my payload app. I can't get drizzle-kit to use the correct version, either the payload app or the nextjs app breaks.

try ```npx drizzle-kit --command```

**Comment by benjick** [comment] 2024-09-25 07:40
@ShaheerCH thanks for the reply, but I'm seeing the same issue with that

```
npx drizzle-kit --version
drizzle-kit: v0.22.1
drizzle-orm: v0.29.3

cat node_modules/drizzle-orm/package.json | grep version
  "version": "0.31.4",
```

**Comment by WisniaFresh** [comment] 2024-10-24 14:06
I updated to:
```
drizzle-kit: v0.20.13
drizzle-orm: v0.29.3
```
and it works <3

**Comment by L-Mario564** [comment] 2024-10-29 17:28
We'll continue to track this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3248.

**Closed by L-Mario564** 2024-10-29 17:28 UTC
