### ISSUE TITLE
404 on localhost:4983/init Impossible to Load Drizzle Studio

### ISSUE THREAD

**Issue by versecafe** [drizzle-team/drizzle-kit-mirror#366] opened 2024-04-19 22:17 UTC
attempting to run `pnpm drizzle-kit studio` starts up on `local.drizzle.studio` but only as a skeleton due to `/init` returning a 404, this is on the latest `0.20.16` and even after downgrading to a previously functioning `0.20.14`

<img width="1312" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/147033096/9ab36323-be1d-4219-a765-74fb9825bdc8">

**Comment by wouter173** [comment] 2024-04-19 23:16
I am getting the exact same issue on both 0.20.15 and 0.20.16

**Comment by JepriCreations** [comment] 2024-04-20 01:49
Same issue with 0.20.16, but rolling back to a preview version (0.20.14, 0.20.15) not solve the problem. An alert is display to force you updating.

<img width="641" alt="SCR-20240420-idry" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/84803700/2180f9fa-ca7d-4725-ae76-1dd50dbd8c69">

**Comment by yash91989201** [comment] 2024-04-20 05:32
I am also getting schema issues while fetching data from db which is as follows 

error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near

which only occurred after I updated to 0.20.16 and now I can't go back to 0.20.14 version , because it's saying to update to latest version

also I haven't changed my db schema it was working perfectly with the 0.20.14 version

**Comment by RomanNabukhotnyi** [comment] 2024-04-20 10:32
@versecafe Hey! Can you please share your schema and logs from browser console?

**Comment by versecafe** [comment] 2024-04-20 17:15
@RomanNabukhotnyi 
<img width="1298" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/147033096/c9f4c35b-a9cb-43ff-adaa-c51829905176">

```ts
import {
  boolean,
  datetime,
  index,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  primaryKey,
  text,
  varchar,
} from "drizzle-orm/mysql-core";

const languages = mysqlEnum("language", [
  "en",
  "es",
  "fr",
  "de",
  "it",
  "pt",
  "nl",
]).notNull();

export const answerTranslationsTable = mysqlTable(
  "answer_translations",
  {
    answerId: int("answer_id")
      .notNull()
      .references(() => answersTable.id),
    language: languages,
    text: varchar("text", { length: 1023 }).notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.answerId, table.language],
      }),
    };
  },
);

export interface Dimension {
  dimension: string;
  position: number;
}

export const answersTable = mysqlTable(
  "answers",
  {
    id: int("id").autoincrement().notNull().primaryKey(),
    questionId: int("question_id")
      .notNull()
      .references(() => questionsTable.id),
    text: varchar("text", { length: 1023 }).notNull(),
    imageUrl: varchar("image_url", { length: 1023 }),
    dimensions: json("dimensions").$type<Dimension[]>().notNull(),
  },
  (table) => {
    return {
      questionAnswersIdx: index("question_answers_index").on(table.questionId),
    };
  },
);

export const articlesTable = mysqlTable("articles", {
  authorId: varchar("author_id", { length: 255 }).references(
    () => usersTable.id,
  ),
  title: varchar("title", { length: 255 }).notNull(),
  content: text("content").notNull(),
  createdAt: datetime("created_at").notNull(),
  imageUrl: varchar("image_url", { length: 1023 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().primaryKey(),
  language: languages.default("en"),
  site: mysqlEnum("site", ["psychometrica", "shared-smiles", "all"])
    .default("all")
    .notNull(),
  published: boolean("published").default(false).notNull(),
  description: varchar("description", { length: 255 }).notNull(),
});

export const communitiesTable = mysqlTable("communities", {
  id: int("id").autoincrement().notNull().primaryKey(),
  published: boolean("published").default(false).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  description: varchar("description", { length: 1023 }).notNull(),
  imageUrl: varchar("image_url", { length: 1023 }).notNull(),
  content: text("content").notNull(),
  weights: json("weights").notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
});

export const communityMembersTable = mysqlTable(
  "community_members",
  {
    userId: varchar("user_id", { length: 255 })
      .notNull()
      .references(() => usersTable.id),
    communityId: int("community_id")
      .notNull()
      .references(() => communitiesTable.id),
    role: mysqlEnum("role", ["member", "moderator", "admin"])
      .default("member")
      .notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.userId, table.communityId],
      }),
    };
  },
);

export const communityTranslationsTable = mysqlTable(
  "community_translations",
  {
    communityId: int("community_id")
      .notNull()
      .references(() => communitiesTable.id),
    language: languages,
    name: varchar("name", { length: 255 }).notNull(),
    description: varchar("description", { length: 1023 }).notNull(),
    content: text("content").notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.communityId, table.language],
      }),
    };
  },
);

export const oauthAccountsTable = mysqlTable(
  "oauth_accounts",
  {
    providerId: varchar("provider_id", { length: 255 }).notNull(),
    providerUserId: varchar("provider_user_id", { length: 255 }).notNull(),
    userId: varchar("user_id", { length: 255 })
      .notNull()
      .references(() => usersTable.id),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.providerId, table.providerUserId],
      }),
    };
  },
);

export const questionTranslationsTable = mysqlTable(
  "question_translations",
  {
    questionId: int("question_id")
      .notNull()
      .references(() => questionsTable.id),
    language: languages,
    text: varchar("text", { length: 1023 }).notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.questionId, table.language],
      }),
    };
  },
);

export const questionsTable = mysqlTable(
  "questions",
  {
    id: int("id").autoincrement().notNull().primaryKey(),
    quizId: int("quiz_id").references(() => quizzesTable.id),
    text: varchar("text", { length: 1023 }).notNull(),
    displayType: mysqlEnum("display_type", [
      "image-grid",
      "image-list",
      "text-grid",
      "text-list",
      "scale",
    ]).notNull(),
    maxChoices: int("max_choices").default(1).notNull(),
    imageUrl: varchar("image_url", { length: 1023 }),
    sourceAnswerId: int("source_answer_id"),
    variant: varchar("variant", { length: 50 }),
  },
  (table) => {
    return {
      quizQuestionsIdx: index("quiz_questions_index").on(table.quizId),
      variantIdx: index("variant_index").on(table.variant),
    };
  },
);

export const quizLandersTable = mysqlTable("quiz_landers", {
  slug: varchar("slug", { length: 255 })
    .primaryKey()
    .notNull()
    .references(() => quizzesTable.slug),
  title: varchar("title", { length: 255 }).notNull(),
  description: varchar("description", { length: 255 }).notNull(),
  content: text("content").notNull(),
});

export const quizTranslationsTable = mysqlTable(
  "quiz_translations",
  {
    quizId: int("quiz_id")
      .notNull()
      .references(() => quizzesTable.id),
    language: languages,
    name: varchar("name", { length: 255 }).notNull(),
    description: varchar("description", { length: 1023 }).notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.quizId, table.language],
      }),
    };
  },
);

export const quizzesTable = mysqlTable(
  "quizzes",
  {
    id: int("id").autoincrement().notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: varchar("description", { length: 1023 }).default("").notNull(),
    skipableQuestions: boolean("skipable_questions").default(false).notNull(),
    published: boolean("published").default(false).notNull(),
    imageUrls: json("image_urls").$type<{
      logo: string;
      tile: string;
      icon: string;
    }>(),
    slug: varchar("slug", { length: 255 }).notNull().unique(),
    category: varchar("category", { length: 255 }).default("").notNull(),
    llmContext: varchar("llm_context", { length: 1023 }).default("").notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({ columns: [table.id], name: "quizzes_id" }),
    };
  },
);

export const quizConfigsTable = mysqlTable(
  "quiz_configs",
  {
    quiz_slug: varchar("quiz_slug", { length: 255 })
      .notNull()
      .references(() => quizzesTable.slug),
    default: boolean("default").notNull().default(false),
    premium: boolean("premium").notNull().default(false),
    estimatedTime: int("estimated_time"),
    title: varchar("title", { length: 255 }).notNull(),
    description: varchar("description", { length: 255 }).notNull(),
    type: mysqlEnum("type", ["static", "dynamic"]).notNull().default("dynamic"),
    shuffle: boolean("shuffle").notNull().default(true),
    variants:
      json("variants").$type<{ variant: string; instances: number }[]>(),
  },
  (table) => {
    return {
      pk: primaryKey({ columns: [table.quiz_slug, table.title] }),
    };
  },
);

export const sessionsTable = mysqlTable("sessions", {
  id: varchar("id", {
    length: 255,
  })
    .notNull()
    .primaryKey(),
  userId: varchar("user_id", {
    length: 255,
  })
    .notNull()
    .references(() => usersTable.id),
  expiresAt: datetime("expires_at").notNull(),
});

export const userAnswersTable = mysqlTable(
  "user_answers",
  {
    userId: varchar("user_id", { length: 255 })
      .notNull()
      .references(() => usersTable.id),
    quizId: int("quiz_id")
      .notNull()
      .references(() => quizzesTable.id),
    answerId: int("answer_id")
      .notNull()
      .references(() => answersTable.id),
    dimensions: json("dimensions").$type<Dimension[]>().notNull(),
  },
  (table) => {
    return {
      pk: primaryKey({
        columns: [table.userId, table.quizId, table.answerId],
      }),
    };
  },
);

export const usersTable = mysqlTable("users", {
  id: varchar("id", { length: 255 }).notNull().primaryKey(),
  username: varchar("username", { length: 255 }).notNull(),
  avatarUrl: varchar("avatar_url", { length: 1023 }),
  email: varchar("email", { length: 255 }),
  role: mysqlEnum("role", ["user", "creator", "moderator", "admin"])
    .default("user")
    .notNull(),
});
```

**Comment by hectorruizlaph** [comment] 2024-04-20 18:17
same here, can't get it to run since upgrade, using ?ssl={"rejectUnauthorized":false}
![Screenshot 2024-04-20 113607](https://github.com/drizzle-team/drizzle-kit-mirror/assets/29240710/f018c1ea-b587-444c-bfaf-719cc75c6751)

**Comment by RomanNabukhotnyi** [comment] 2024-04-20 20:34
@versecafe @hectorruizlaph Can you try a hard refresh in browser?

**Comment by versecafe** [comment] 2024-04-20 20:37
@hectorruizlaph  Tried hard refreshes, cache clears, and wiping node modules and a full reboot

**Comment by RomanNabukhotnyi** [comment] 2024-04-20 21:18
Can you provide responses from requests to localhost? Or just check maybe there error in response

**Comment by kimjisena** [comment] 2024-04-20 22:20
Same here...It was working just fine but then now it's returning 404 and forcing me to upgrade even though I'm on the latest version.

**Comment by RomanNabukhotnyi** [comment] 2024-04-20 22:47
@kimjisena Hey! Do you have version 0.20.17? If yes then maybe try reinstalling

**Comment by hectorruizlaph** [comment] 2024-04-20 23:04
@versecafe @kimjisena I've tried everything, with no success, I'm using "next": "^14.1.3",  "drizzle-kit": "^0.20.17",  "mysql2": "^3.6.1", pnpm

**Comment by JepriCreations** [comment] 2024-04-21 05:34
For me, it started working again with 0.20.16 when I deleted my local database and created it again (I am using Turso local development), and uninstalled drizzle-kit, and installed it again. After updating to 0.20.17, everything is still working fine. I'm not sure what really fixed it though.

**Comment by kimjisena** [comment] 2024-04-21 08:02
> @kimjisena Hey! Do you have version 0.20.17? If yes then maybe try reinstalling

I tried reinstalling everything to no avail.

One thing I haven't tried is dropping the database and rerunning migrations (as someone has suggested in the thread). Let me try that too.

**Comment by RomanNabukhotnyi** [comment] 2024-04-21 08:24
@kimjisena Can you provide database url without credentials?

**Comment by kimjisena** [comment] 2024-04-21 08:31
> @kimjisena Can you provide database url without credentials?

here's the contents of my drizzle config
```ts
// drizzle.config.ts
import "dotenv/config";
import type { Config } from "drizzle-kit";

export default {
  schema: "./src/db/schemas/index.ts",
  out: "./src/db/migrations",
  driver: "pg", // 'pg' | 'mysql2' | 'better-sqlite' | 'libsql' | 'turso'
  dbCredentials: {
    host: process.env.PG_HOST as string,
    port: Number(process.env.PG_PORT),
    user: process.env.PG_USER,
    password: process.env.PG_PASSWORD,
    database: process.env.PG_NAME as string,
  },
} satisfies Config;
```

**Comment by RomanNabukhotnyi** [comment] 2024-04-21 08:33
> > @kimjisena Can you provide database url without credentials?
> 
> here's the contents of my drizzle config
> 
> ```ts
> // drizzle.config.ts
> import "dotenv/config";
> import type { Config } from "drizzle-kit";
> 
> export default {
>   schema: "./src/db/schemas/index.ts",
>   out: "./src/db/migrations",
>   driver: "pg", // 'pg' | 'mysql2' | 'better-sqlite' | 'libsql' | 'turso'
>   dbCredentials: {
>     host: process.env.PG_HOST as string,
>     port: Number(process.env.PG_PORT),
>     user: process.env.PG_USER,
>     password: process.env.PG_PASSWORD,
>     database: process.env.PG_NAME as string,
>   },
> } satisfies Config;
> ```

Oh, you're using Postgres. Then can you show your schema?

**Comment by kimjisena** [comment] 2024-04-21 08:41
> > > @kimjisena Can you provide database url without credentials?
> > 
> > 
> > here's the contents of my drizzle config
> > ```ts
> > // drizzle.config.ts
> > import "dotenv/config";
> > import type { Config } from "drizzle-kit";
> > 
> > export default {
> >   schema: "./src/db/schemas/index.ts",
> >   out: "./src/db/migrations",
> >   driver: "pg", // 'pg' | 'mysql2' | 'better-sqlite' | 'libsql' | 'turso'
> >   dbCredentials: {
> >     host: process.env.PG_HOST as string,
> >     port: Number(process.env.PG_PORT),
> >     user: process.env.PG_USER,
> >     password: process.env.PG_PASSWORD,
> >     database: process.env.PG_NAME as string,
> >   },
> > } satisfies Config;
> > ```
> 
> Oh, you're using Postgres. Then can you show your schema?

Yes, I'm using Postgres. Actually, in the initial set up I was using MySQL and it was working fine (I even tweeted about it). But then I decided to switch to Postgres so I updated my schemas and everything. I can generate migrations just fine and I can run them. All tables are being created correctly but Drizzle Studio is somehow not working.

As for schemas, I have several schema files that I have re-exported in one file (see code below):
```ts
// ./src/db/schemas/index.ts
export { asset } from "./asset";
export { availability } from "./availability";
export { chef } from "./chef";
export { chefAvailability } from "./chef-availability";
export { chefDish } from "./chef-dish";
export { chefOrder } from "./chef-order";
export { chefReview } from "./chef-review";
export { chefTransaction } from "./chef-transaction";
export { dish } from "./dish";
export { dishAsset } from "./dish-asset";
export { dishReview } from "./dish-review";
export { favoriteChef } from "./favorite-chef";
export { favoriteDish } from "./favorite-dish";
export { favoriteRestaurant } from "./favorite-restaurant";
export { group } from "./group";
export { groupMessage } from "./group-message";
export { menu } from "./menu";
export { menuDish } from "./menu-dish";
export { message, messageTypeEnum } from "./message";
export { messageAsset } from "./message-asset";
export { order, orderStatusEnum } from "./order";
export { orderAvailability } from "./order-availability";
export { payment, paymentStatusEnum } from "./payment";
export { point } from "./point";
export { redemptionHistory } from "./redemption-history";
export { restaurant } from "./restaurant";
export { restaurantAvailability } from "./restaurant-availability";
export { restaurantDish } from "./restaurant-dish";
export { restaurantOrder } from "./restaurant-order";
export { restaurantReview } from "./restaurant-review";
export { restaurantTransaction } from "./restaurant-transaction";
export { review } from "./review";
export { reviewAsset } from "./review-asset";
export { reward } from "./reward";
export {
  transaction,
  transactionStatusEnum,
  transactionTypeEnum,
} from "./transaction";
export { userGroup } from "./user-group";
export { userMessage } from "./user-message";
export { user, userRoleEnum, userStatusEnum } from "./user";
```

**Comment by RomanNabukhotnyi** [comment] 2024-04-21 08:50
@kimjisena And you also have this error?
<img width="383" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/97584054/29faf526-1521-4b78-849d-d47b16e6c6b5">

**Comment by kimjisena** [comment] 2024-04-21 08:54
> @kimjisena And you also have this error? <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/97584054/324234872-29faf526-1521-4b78-849d-d47b16e6c6b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODk3MzcsIm5iZiI6MTcxMzY4OTQzNywicGF0aCI6Ii85NzU4NDA1NC8zMjQyMzQ4NzItMjlmYWY1MjYtMTUyMS00Yjc4LTg0OWQtZDQ3YjE2ZTZjNmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA4NTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2N2ZlMDcyN2MwN2ViYjc2NWY4N2RiYjJlMmNlNjU3OGU5NWUyZjE5NzZkYWQ5OWUzNDEyMjZmMmU1OTdhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9nrGQk-ywICyC0SdTC7X_hG3LHV2UG9_ljCwwmqC2kI">

Not exactly...error on my end is "Invalid API version"
<img width="897" alt="Screenshot 2024-04-21 at 11 52 42" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/73499939/4cc709d4-189d-4f13-a1f6-bfef0d5ac873">

**Comment by RomanNabukhotnyi** [comment] 2024-04-21 08:58
@kimjisena Then try removing the node_modules and package lock file and reinstalling the dependencies (also check that you have the latest version of drizzle-kit)

**Comment by kimjisena** [comment] 2024-04-21 09:07
> @kimjisena Then try removing the node_modules and package lock file and reinstalling the dependencies (also check that you have the latest version of drizzle-kit)

At first I was just removing `node_modules` and left the lock files as they were.

This finally worked. Thanks!
```
# remove `node_modules` and all lock files
rm -fr node_modules bun.lockb yarn.lock 

# reinstall dependencies
bun install
```

**Comment by stefanikostic** [comment] 2024-04-22 08:26
> @kimjisena Then try removing the node_modules and package lock file and reinstalling the dependencies (also check that you have the latest version of drizzle-kit)

I've tried removing the node_modules and pnpm_lock.yaml file and reinstalling the dependencies (using drizzle-kit 0.20.17) and I still have this issue
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/36265650/811d7918-05e4-4681-a27e-ddd7f3d88fc5)


Any suggestions what can I do next?

**Comment by RomanNabukhotnyi** [comment] 2024-04-22 12:33
@stefanikostic Hey! Can you please share your schema?

**Comment by stefanikostic** [comment] 2024-04-22 12:45
> @stefanikostic Hey! Can you please share your schema?


Yes, here it is 
import { relations } from 'drizzle-orm';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const quizzes = sqliteTable('quizzes', {
  id: integer('id').primaryKey(),
  name: text('name').notNull().unique(),
  description: text('description'),
  isPublished: integer('is_published', { mode: 'boolean' }).default(false),
});

export const quizRelations = relations(quizzes, ({ many }) => ({
  questions: many(questions),
}));

export const questions = sqliteTable('questions', {
  id: integer('id').primaryKey(),
  quizId: integer('quiz_id')
    .notNull()
    .references(() => quizzes.id, { onDelete: 'cascade' }),
  text: text('text').notNull(),
  duration: integer('duration').notNull(),
  points: integer('points').notNull(),
});

export const questionsRelations = relations(questions, ({ one, many }) => ({
  quiz: one(quizzes, {
    fields: [questions.quizId],
    references: [quizzes.id],
  }),
  answers: many(answers),
}));

export const answers = sqliteTable('answers', {
  id: integer('id').primaryKey(),
  questionId: integer('question_id')
    .notNull()
    .references(() => questions.id, { onDelete: 'cascade' }),
  text: text('text').notNull(),
  isCorrect: integer('is_correct', { mode: 'boolean' }),
});

export const answersRelations = relations(answers, ({ one }) => ({
  question: one(questions, {
    fields: [answers.questionId],
    references: [questions.id],
  }),
}));

**Comment by ecwyne** [comment] 2024-04-22 18:51
Having the same issue here. No workaround

**Comment by vieko** [comment] 2024-04-25 23:19
+1 on this issue.

mysql
drizzle-kit: v0.20.17
drizzle-orm: v0.30.9

**Comment by eslym** [comment] 2024-04-30 02:25
I am seeing bun default page while using bun
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/3667594/28e0309a-762b-47b9-8da2-afc0e296f5a6)

and then ofc cors failed
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/3667594/b5ac2660-f58a-49b1-8c40-c2ae96d7741f)

**Comment by bielarusajed** [comment] 2024-05-05 13:08
+1 here.
drizzle-kit@0.20.17
It sends requests to the `http://localhost:4983/init` and `https://localhost:4983/init`, and the http one is with an empty response, https one is with 404: 
<img width="560" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/90352332/41bc984a-969e-4b8c-bee9-abaee35c2c53">

My `drizzle.config.ts`:
```typescript
import type { Config } from 'drizzle-kit';

export default {
  schema: './src/schema/*',
  out: './migrations',
  driver: 'pg',
  dbCredentials: {
    connectionString: process.env.DATABASE_URL!,
  },
} satisfies Config;

```

Running on Node v20.10.0.

**Comment by josean-dev** [comment] 2024-05-05 16:19
+1 on this issue

Also happening to me on Chrome.

postgres
drizzle-kit: v0.20.17
drizzle-orm: v0.30.10

**Comment by AlexBlokh** [comment] 2024-06-18 09:52
@josean-dev @bielarusajed @eslym @vieko @sveenxx @ecwyne @stefanikostic @kimjisena @versecafe @JepriCreations @wouter173 

I've tried with/without bun with/without environment variables, tried `mysql`, `sqlite` and `postgresql` on the latest `0.22.7` as of now version and it works perfectly fine

please keep in mind Drizzle Studio does both `http` and `https` requests to find out whether server is with or without `mkcert` so there will always be failed requests in the logs and it's perfectly fine

I'm closing the issues and if something will pop up in the newer version - please open a new issue, thanks!

**Closed by AlexBlokh** 2024-06-18 09:52 UTC

**Comment by AlexBlokh** [comment] 2024-06-24 16:09
hey, @k2on 
please provide a minimal reproducible example and/or more context on browser/OS, etc

**Comment by k2on** [comment] 2024-07-12 04:49
> hey, @k2on 
> 
> please provide a minimal reproducible example and/or more context on browser/OS, etc

Yeah my bad.
