### ISSUE TITLE
Bun support with `--bun`

### ISSUE THREAD

**Issue by mikerockett** [drizzle-team/drizzle-kit-mirror#199] opened 2023-09-25 11:08 UTC
I am trying to execute drizzle-kit commands using bun (instead of passing it off to `node` by way of the default shebang).

For example:

```
bun run --bun drizzle-kit generate:pg
```

or via `package.json`:

```jsonc
{
  "scripts": {
    "db:generate": "bun run --bun drizzle-kit generate:pg"
    // $ bun run db:generate
  }
}
```

When I do this, the command executes, but it cannot see my schema files. If I generated previously with node (ie, via the default shebang), and then with bun, it would generate a migration that drops all tables.

Output of the above command is always as if no schema files were present.

### Drizzle Kit Config

```ts
import type { Config } from 'drizzle-kit'

export default {
  driver: 'pg',
  dbCredentials: { connectionString: process.env.DATABASE_URL! },
  schema: './lib/db/schema/*.ts',
  out: './lib/db/migrations',
  introspect: { casing: 'preserve' },
  schemaFilter: ['public'],
  strict: true,
  verbose: true,
} satisfies Config

```

Could it be because I am globbing the schema? Or, am I missing something?

### Versions:

```shell
$ bun pm ls | grep drizzle
[0.03ms] ".env"
├── drizzle-kit@0.19.13
├── drizzle-orm@0.28.6
```

**Comment by hazelnutcloud** [comment] 2023-10-16 03:05
can confirm facing this issue too

**Comment by ben-xD** [comment] 2023-11-11 10:05
`bun run --bun drizzle-kit generate:pg` worked for me.

I use `nodenext` and `.js` imports though. Not sure if that's relevant.

**Comment by SnowMarble** [comment] 2023-11-23 16:20
I found another way to fix it. It's kind of working, but we can use `export` in schema.ts

First, go to `node_modules/drizzle-kit/bin.js` and find `src/serializer/<your-driver>Imports.ts`(pg for `pgImports.ts` and mysql for `mysqlImports.ts`).

And, change `forEach` statement in `prepareFromExports` or `prepareFromMySqlImports`(function that contains `forEach`) to `for ... in` statement.
For example, we can fix pg like this:

```ts
// bin.js:12048
prepareFromExports = (exports) => {
  const tables = [];
  const enums = [];
  const schemas = [];
  for(let e in exports) {
    const t = exports[e];
    if ((0, import_pg_core.isPgEnum)(t)) {
      enums.push(t);
      continue;
    }
    if ((0, import_drizzle_orm4.is)(t, import_pg_core.PgTable)) {
      tables.push(t);
    }
    if ((0, import_drizzle_orm4.is)(t, import_pg_core.PgSchema)) {
      schemas.push(t);
    }
  }
  return { tables, enums, schemas };
};
```

Lastly, follow [this comment](https://github.com/oven-sh/bun/issues/2336#issuecomment-1712458657) to apply the change.

The problem is that Bun's `Object.values` or `Object.keys` for the Module object (a return value of `require`) give us nothing unlike Nodejs.

```ts
const schema = require('./db/schema.ts')
const exports = Object.values(schema) // []
```

and somehow for ... in can iterate the object even in Bun.

**Comment by malvinpratama** [comment] 2023-12-17 07:48
> I found another way to fix it. It's kind of working, but we can use `export` in schema.ts
> 
> First, go to `node_modules/drizzle-kit/bin.js` and find `src/serializer/<your-driver>Imports.ts`(pg for `pgImports.ts` and mysql for `mysqlImports.ts`).
> 
> And, change `forEach` statement in `prepareFromExports` or `prepareFromMySqlImports`(function that contains `forEach`) to `for ... in` statement. For example, we can fix pg like this:
> 
> ```ts
> // bin.js:12048
> prepareFromExports = (exports) => {
>   const tables = [];
>   const enums = [];
>   const schemas = [];
>   for(let e in exports) {
>     const t = exports[e];
>     if ((0, import_pg_core.isPgEnum)(t)) {
>       enums.push(t);
>       continue;
>     }
>     if ((0, import_drizzle_orm4.is)(t, import_pg_core.PgTable)) {
>       tables.push(t);
>     }
>     if ((0, import_drizzle_orm4.is)(t, import_pg_core.PgSchema)) {
>       schemas.push(t);
>     }
>   }
>   return { tables, enums, schemas };
> };
> ```
> 
> Lastly, follow [this comment](https://github.com/oven-sh/bun/issues/2336#issuecomment-1712458657) to apply the change.
> 
> The problem is that Bun's `Object.values` or `Object.keys` for the Module object (a return value of `require`) give us nothing unlike Nodejs.
> 
> ```ts
> const schema = require('./db/schema.ts')
> const exports = Object.values(schema) // []
> ```
> 
> and somehow for ... in can iterate the object even in Bun.

it's works.
can you create PR for this ?
I think this major issue for drizzle-kit if we want to support bun.

**Comment by SnowMarble** [comment] 2023-12-17 07:58
@malvinpratama Unfortunately, drizzle kit is not an open source that we can't make a contrubution right away. But we can mention drizzle team to let them know about it.

**Comment by itsyoboieltr** [comment] 2024-01-09 00:42
Looking forward to this fix! I only need to install node on my docker image so I can run drizzle-kit, everything else is already running with bun.

**Comment by gnosticdev** [comment] 2024-03-14 21:33
For those having the same issue with sqlite, you can patch by changing `require` to `await import` in the `prepareFromSqliteImports` function.

```ts
// node_modules/drizzle-kit/bin.cjs: 12840
 prepareFromSqliteImports = async (imports) => {
      const tables = [];
      const enums = [];
      const { unregister } = await safeRegister();
      for (let i = 0; i < imports.length; i++) {
        const it = imports[i];
        // const i0 = require(`${it}`); <-- does not work with --bun flag
        const i0 = await import(`${it}`); // <-- this works with --bun
        const i0values = Object.values(i0);
        i0values.forEach((t) => {
          if ((0, import_drizzle_orm6.is)(t, import_sqlite_core.SQLiteTable)) {
            tables.push(t);
          }
        });
      }
```

Also, from instructions above:

1. add yarn.lock and patch-package:
```sh
 bun i --yarn && bunx patch-package drizzle-kit
```
2. make the change above
3. add `postinstall: bunx patch-package` to package.json scripts
4. delete `yarn.lock`

Thanks @SnowMarble  for the fix!

**Comment by GoncaloJoseMoura** [comment] 2024-09-13 00:54
this problem still persists.

**Comment by L-Mario564** [comment] 2024-10-29 19:10
According to Jarred Summer (creator and maintainer of Bun), this should be fixed and seemed to be a bug with the Bun runtime. If this bug persists I suggest following Jarred's instructions to re-open the issue on the Bun repo: https://github.com/oven-sh/bun/issues/8545#issuecomment-2430453360. If the issue persists and Bun works as intended, feel free to file a new issue on the main repo of Drizzle ORM: https://github.com/drizzle-team/drizzle-orm/issues.

**Closed by L-Mario564** 2024-10-29 19:10 UTC
