### ISSUE TITLE
Cannot find module "drizzle-orm/version"

### ISSUE THREAD

**Issue by yamiteru** [drizzle-team/drizzle-kit-mirror#52] opened 2023-05-16 23:47 UTC
```bash
$ drizzle-kit generate:sqlite
drizzle-kit: v0.17.6

node:internal/modules/cjs/loader:1082
  const err = new Error(message);
              ^

Error: Cannot find module 'drizzle-orm/version'
Require stack:
- /Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at assertOrmCoreVersion (/Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js:49408:36)
    at Command2.<anonymous> (/Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js:49680:3)
    at Command2.listener [as _actionHandler] (/Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js:827:21)
    at /Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js:1246:69
    at Command2._chainOrCall (/Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js:1178:16)
    at Command2._parseCommand (/Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js:1246:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yamiteru/dev/h2-organizer/node_modules/drizzle-kit/index.js'
  ]
}

Node.js v20.1.0
```

I can see that the "version" files (version.cjs/mjs) are in `drizzle-orm` in node_modules.

**Comment by madebyfabian** [comment] 2023-05-17 07:56
Can confirm, having the same issue:

```bash
drizzle-kit: v0.17.6

node:internal/modules/cjs/loader:985
  const err = new Error(message);
              ^

Error: Cannot find module 'drizzle-orm/version'
Require stack:
- /Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at assertOrmCoreVersion (/Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js:49408:36)
    at Command2.<anonymous> (/Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js:49648:3)
    at Command2.listener [as _actionHandler] (/Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js:827:21)
    at /Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js:1246:69
    at Command2._chainOrCall (/Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js:1178:16)
    at Command2._parseCommand (/Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js:1246:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/fabian/Library/pnpm/store/v3/tmp/dlx-7390/node_modules/.pnpm/drizzle-kit@0.17.6/node_modules/drizzle-kit/index.js'
  ]
}
 ERROR  Command failed with exit code 1: drizzle-kit generate:pg

pnpm: Command failed with exit code 1: drizzle-kit generate:pg
    at makeError (/Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:24235:17)
    at handlePromise (/Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:24806:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (/Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:212270:7)
    at async /Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:221602:21
    at async main (/Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:221569:34)
    at async runPnpm (/Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:221824:5)
    at async /Users/fabian/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:221816:7
```

using:
"drizzle-orm": "^0.25.4",
"drizzle-kit": "^0.17.6",

**Comment by AndriiSherman** [comment] 2023-05-17 12:42
Do you have `drizzle-kit` installed in same project as `drizzle-orm`?

**Comment by yamiteru** [comment] 2023-05-17 12:51
Yes

**Comment by madebyfabian** [comment] 2023-05-17 12:52
@AndriiSherman Thanks for your answer

Yes I do. This is the full package.json:

```json
{
	"name": "nuxt-app",
	"private": true,
	"scripts": {
		"build": "nuxt build",
		"start": "nuxt dev",
		"generate": "nuxt generate",
		"preview": "nuxt preview",
		"postinstall": "nuxt prepare"
	},
	"devDependencies": {
		"@types/node": "^18",
		"@types/pg": "^8.6.6",
		"drizzle-kit": "^0.17.6",
		"nuxt": "^3.5.0"
	},
	"dependencies": {
		"drizzle-orm": "^0.25.4",
		"pg": "^8.11.0"
	}
}
```

and the drizzle.config.json

```json
{
	"out": "./migrations",
	"schema": "./server/utils/schema",
	"breakpoints": false
}
```

And I tried to generate it with `npx drizzle-kit generate:pg`, just like in the docs. Which should access the npm version, not the local one, right?

**Comment by yamiteru** [comment] 2023-05-17 12:53
I use it in a monorepo with yarn and Node20 (tried also with 18).

**Comment by AndriiSherman** [comment] 2023-05-17 16:23
I can confirm, that it's better to write a package.json script and use drizzle-kit from there and not globally cc @madebyfabian
We will just need to update docs for that(we already have, will deploy it soon)

@yamiteru as I can see you are using drizzle-kit from package.json script. In this case you shouldn't;t have such issue. Will try to reproduce it

**Comment by yamiteru** [comment] 2023-05-18 10:12
@AndriiSherman were you able to reproduce it? It also happens to my team mates.

**Comment by AndriiSherman** [comment] 2023-05-18 10:28
@yamiteru can't reproduce it but maybe I've done not the exact steps you did

Could you please share some repo with some minimal reproducible example (just 1 schema table), so I can run exact same setup and will try to debug it?

**Comment by yamiteru** [comment] 2023-05-18 12:20
@AndriiSherman you actually don't need any example repo for this. 

I've just tried this on a completely new computer.

I've opened terminal and typed these commands:
1. `mkdir test`
2. `cd test`
3. `npx drizzle-kit generate:sqlite`

It's giving me this error:

```shell
drizzle-kit: v0.17.6

node:internal/modules/cjs/loader:1070
  const err = new Error(message);
              ^

Error: Cannot find module 'drizzle-orm/version'
Require stack:
- /Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at assertOrmCoreVersion (/Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js:49408:36)
    at Command2.<anonymous> (/Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js:49680:3)
    at Command2.listener [as _actionHandler] (/Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js:827:21)
    at /Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js:1246:69
    at Command2._chainOrCall (/Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js:1178:16)
    at Command2._parseCommand (/Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js:1246:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yamiteru/.npm/_npx/7c7555b0b81cc7e0/node_modules/drizzle-kit/index.js'
  ]
}

Node.js v20.2.0
```

I've tried this with Node versions 16/18/20 and neither one works. All of them show this exact same error.

I'm on the latest version of MacOS.

**Comment by AndriiSherman** [comment] 2023-05-18 12:25
So this one is expected behavior. You need to install `drizzle-kit` in your node_modules together with `drizzle-orm`. And you need to invoke `drizzle-kit generate:pg` from your package.json scripts and not globally

Currently, they can't exist separately

**Comment by yamiteru** [comment] 2023-05-18 12:44
I've tried creating a minimal reproduction but it works.. 

Maybe it has something to do with monorepo?

**Comment by madebyfabian** [comment] 2023-05-18 14:39
@AndriiSherman I managed to get it to work by adding the command to the "script" section in the package.json and then do npm run generate:pg. Update on the docs appreciated. Thanks! 💪

**Comment by fjeldstad** [comment] 2024-02-13 12:22
The suggested solution does not work if NPM for one reason or another decides to install `drizzle-orm` in a workspace-local `node_modules` while it installs `drizzle-kit` in the root - even if both are defined in the workspace package.json. One cannot really control where it puts them as far as I know, since peer dependency conflicts seem to affect the decision. 

See post on Discord for example: https://discord.com/channels/1043890932593987624/1206922205552709652

**Comment by kasbah** [comment] 2024-04-05 14:02
This is likely the same issue as https://github.com/drizzle-team/drizzle-orm/issues/1135

**Comment by L-Mario564** [comment] 2024-10-28 17:35
This should be fixed in latest. If a similar issue is still present, please file a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.

**Closed by L-Mario564** 2024-10-28 17:35 UTC
