### ISSUE TITLE
Issue when generating sql using zod for environment variable validation

### ISSUE THREAD

**Issue by STNeto1** [drizzle-team/drizzle-kit-mirror#21] opened 2023-03-20 01:11 UTC
When using `npx drizzle-kit generate:mysql` with other source for env variables, an error is thrown.

```sh
npx drizzle-kit generate:mysql       
drizzle-kit: v0.17.0
drizzle-orm: v0.22.0-88c1ad3

/home/stneto/apps/edge-shortener/src/env.mjs:2
import { z } from "zod";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

The .env validation comes from [here](https://create.t3.gg/en/usage/env-variables/)

The issue on code can be found [here](https://github.com/STNeto1/edge-shortener/blob/main/src/db/db.ts#L13-L17)

**Comment by karmux** [comment] 2023-03-26 14:45
I also get `SyntaxError: Cannot use import statement outside a module` from the first import of helper package when I run `drizzle-kit generate:pg`.

**Comment by AndriiSherman** [comment] 2023-03-27 07:28
@karmux @STNeto1 do you have anything else in file with schemas except of tables/enums? 
Ideally is to have `schema.ts`(Or any name you want to use for this file) containing only database schema definitions

**Comment by STNeto1** [comment] 2023-03-27 10:17
The current files

```tsx
// DB
import { connect } from "@planetscale/database";
import { drizzle } from "drizzle-orm/planetscale-serverless";
import { env } from "~/env.mjs";

const connection = connect({
  host: env.DATABASE_HOST,
  username: env.DATABASE_USERNAME,
  password: env.DATABASE_PASSWORD,
});

export const db = drizzle(connection, {
  logger: true,
});

// =============

// SCHEMA
import {
  serial,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core/columns";
import { mysqlTable } from "drizzle-orm/mysql-core/table";

export const shortLink = mysqlTable("short_links", {
  id: serial("id").primaryKey(),
  url: text("url").notNull(),
  slug: varchar("slug", {
    length: 20,
  }).notNull(),
  created_at: timestamp("created_at").notNull().defaultNow(),
});
```

I can't see anything else being imported that would cause the issue

**Comment by karmux** [comment] 2023-03-27 22:36
I'm importing own esm package to schemas that contains some convenience helper functions.

Minimum reproducible example:

```
// add these two lines to the header of schemas.ts
import { createTimestampColumns } from 'drizzle-utils';
console.log(createTimestampColumns());
```

Download and install as local dependency of an app that has migrations:
[drizzle-utils.tar.gz](https://github.com/drizzle-team/drizzle-kit-mirror/files/11083445/drizzle-utils.tar.gz)

```
// under dependencies of package.json
"drizzle-utils": "../drizzle-utils",
```

This triggers `SyntaxError: Cannot use import statement outside a module` error when trying to generate migration.

**Comment by mikebuilds** [comment] 2023-05-22 06:26
Did you get this working?

**Comment by karmo-sisutech** [comment] 2023-05-31 11:17
No. Andrew in Discord said that he reproduced it and started working on it.

**Comment by deadcoder0904** [comment] 2024-02-06 09:43
would like support for `t3-env` or some other way to read environment variables?

see https://github.com/t3-oss/t3-env/issues/180 for more.

in my next.js app, everything works but i wish `drizzle-kit` has some built-in support for it because those are the only commands that fail to read `.env` file or check validations. i wish it somehow works magically.

**Comment by L-Mario564** [comment] 2024-10-28 18:07
Will be closing this in favor of issues related to Kit and ESM support over on the main repo.

**Closed by L-Mario564** 2024-10-28 18:07 UTC
