### ISSUE TITLE
Introspect:pg breaks on multiple primary keys

### ISSUE THREAD

**Issue by MAST1999** [drizzle-team/drizzle-kit-mirror#135] opened 2023-07-26 10:55 UTC
I was trying to introspect our database but it ends up with this error:
```
[✓] 63   tables fetched
[⣟] 1537 columns fetching
[⣟] 0    enums fetching
[⣟] 0    indexes fetching
[⣟] 218  foreign keys fetching
/home/mast/workspace/work/mix-optimization-dashboard/node_modules/.pnpm/drizzle-kit@0.19.11/node_modules/drizzle-kit/index.cjs:12431
                  name: tableCompositePkName[0].primary_key,
                                                ^

TypeError: Cannot read properties of undefined (reading 'primary_key')
    at /home/mast/workspace/work/mix-optimization-dashboard/node_modules/.pnpm/drizzle-kit@0.19.11/node_modules/drizzle-kit/index.cjs:12431:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

We have quite a few tables so it's kinda hard to figure out which table has a problem.

**Comment by AndriiSherman** [comment] 2023-07-26 10:57
@MAST1999 what drizzle-kit version do you have?

**Comment by AndriiSherman** [comment] 2023-07-26 15:09
Trying to reproduce it, and so far no lack. I guess I'll need to have some minimal reproducible example from you

**Comment by MAST1999** [comment] 2023-07-26 18:03
Oh, I'm using schema filters. That might affect it.

@AndriiSherman

**Comment by nhedger** [comment] 2023-07-27 17:57
Hey, I encountered the same issue in my project.

I was able to create a minimal reproduction.

- https://github.com/nhedger/drizzle-kit-issue-135

It seems this only happens when using a schema name different than `public`.

**Comment by harrismcc** [comment] 2023-08-03 21:32
I'm having the exact same issue. With my `schemaFilter` being `schemaFilter: ['auth']`.

**Comment by phiresky** [comment] 2023-08-10 20:02
same. the issue is that it filters by `conrelid::regclass::text = $1 = tablename` but for non-default schema (public) conrelid::regclass is `schemaname.tablename` and not `tablename`

**Comment by phiresky** [comment] 2023-08-10 20:09
Changing the `const tableCompositePkName = ...` line in index.cjs to this:

```ts
 const tableCompositePkName = await db.query(
                  `SELECT conname AS primary_key
                FROM   pg_constraint join pg_class on (pg_class.oid = conrelid)
                WHERE  contype = 'p' 
                AND    connamespace = $1::regnamespace  
                AND    pg_class.relname = $2;`,
                [tableSchema, tableName]
                );
```

fixes it. i'd open a pr but i guess this library isn't actually open source?

**Comment by AndriiSherman** [comment] 2023-08-10 20:12
@phiresky thanks a lot! I’ll test your code and will add to contributors in release. After we will open source this repo we are going to list everyone who helped us the same way you did in readme and website!

**Comment by MAST1999** [comment] 2023-09-05 18:48
Is there any way to get this into the next release?
I've moved our production to drizzle and the only thing that is missing from our work flow is using drizzle kit for migration generation and introspecting the database.

No pressure though, just want to get a time period that I can give to the team.

**Comment by zknicker** [comment] 2023-09-20 02:08
> Changing the `const tableCompositePkName = ...` line in index.cjs to this:
> 
> ```ts
>  const tableCompositePkName = await db.query(
>                   `SELECT conname AS primary_key
>                 FROM   pg_constraint join pg_class on (pg_class.oid = conrelid)
>                 WHERE  contype = 'p' 
>                 AND    connamespace = $1::regnamespace  
>                 AND    pg_class.relname = $2;`,
>                 [tableSchema, tableName]
>                 );
> ```
> 
> fixes it. i'd open a pr but i guess this library isn't actually open source?

Worked for me as well, would love to see this get merged soon!

**Comment by AndriiSherman** [comment] 2023-11-21 12:28
Should be fixed on `drizzle-kit@pk-issue`. Will deploy to latest soon
Would be great if you can check this tag

**Comment by jakeleventhal** [comment] 2023-12-28 15:39
I am running into this same issue with `drizzle-kit@0.20.9`

**Closed** 2024-10-29 18:26 UTC
